name = "PotentialCalculation"
uuid = "76415700-ec45-11e8-0f65-f1df3c899b21"
authors = ["Teemu Järvinen <teemu.j.jarvinen@student.jyu.fi>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
